# github action to deploy weather application

name: Deploy weather forecast API

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore ./WeatherForecast.cs

      - name: Build
        run: dotnet build ./WeatherForecast.cs


    