# github action to deploy weather application

name: Deploy weather forecast API

on:
  workflow_dispatch:

env: 
  AZURE_WEBAPP_NAME: "WebApplicationCICD20240802164718"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore ./WebApplicationCICD/WebApplicationCICD.csproj

      - name: Build
        run: dotnet build ./WebApplicationCICD/WebApplicationCICD.csproj --configuration Release --no-restore


    # publish
      - name: Publish
        run: dotnet publish ./WebApplicationCICD/WebApplicationCICD.csproj --configuration Release --output ./publish

   # deploytoazure
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
	uses: azure/webapps-deploy@v2
	with:
	  app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
	  package: ./publish